import React, { useState, useEffect, useMemo } from 'react';
import {
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Clock,
  Lock,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  Circle,
  CalendarCheck,
} from 'lucide-react';
import { fetchSchedule, runScheduler } from '../api/schedule';
import { fetchRoutineBlocks } from '../api/routine';
import Button from './ui/Button';
import Badge from './ui/Badge';
import Skeleton from './ui/Skeleton';
import EmptyState from './ui/EmptyState';

export default function TimelineView({ onCompleteItem, onToast }) {
  const getTodayStr = () => new Date().toISOString().split('T')[0];

  const [selectedDate, setSelectedDate] = useState(getTodayStr);
  const [slots, setSlots] = useState([]);
  const [routineBlocks, setRoutineBlocks] = useState([]);
  const [unplaceableItems, setUnplaceableItems] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isScheduling, setIsScheduling] = useState(false);

  // Load schedule slots and routine blocks for selected date
  const loadDayData = async (targetDate = selectedDate) => {
    setIsLoading(true);
    try {
      const d = new Date(targetDate + 'T00:00:00');
      const jsDay = d.getDay();
      const pythonWeekday = jsDay === 0 ? 6 : jsDay - 1;

      const [slotsData, routineData] = await Promise.all([
        fetchSchedule(targetDate),
        fetchRoutineBlocks(pythonWeekday),
      ]);

      setSlots(slotsData);
      setRoutineBlocks(routineData);
    } catch (err) {
      onToast?.(err.message || 'Failed to load timeline', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadDayData(selectedDate);
  }, [selectedDate]);

  const handleDateChange = (daysDelta) => {
    const current = new Date(selectedDate + 'T00:00:00');
    current.setDate(current.getDate() + daysDelta);
    const newDateStr = current.toISOString().split('T')[0];
    setSelectedDate(newDateStr);
  };

  const handleRunScheduler = async () => {
    setIsScheduling(true);
    try {
      const result = await runScheduler(selectedDate);
      setSlots(result.slots || []);
      setUnplaceableItems(result.unplaceable_items || []);

      if (result.scheduled_count > 0) {
        onToast?.(`Scheduled ${result.scheduled_count} item(s)!`);
      } else if (result.unplaceable_count > 0) {
        onToast?.(`No free slots available for remaining items`, 'error');
      } else {
        onToast?.('Schedule up to date — no pending items');
      }
    } catch (err) {
      onToast?.(err.message || 'Failed to run scheduler', 'error');
    } finally {
      setIsScheduling(false);
    }
  };

  const timelineItems = useMemo(() => {
    const combined = [];

    routineBlocks.forEach((rb) => {
      combined.push({
        type: 'routine',
        id: `rb-${rb.id}`,
        startTime: rb.start_time.slice(0, 5),
        endTime: rb.end_time.slice(0, 5),
        label: rb.label || 'Routine Block',
        fixed: rb.fixed,
      });
    });

    slots.forEach((s) => {
      combined.push({
        type: 'slot',
        id: `slot-${s.id}`,
        slotId: s.id,
        startTime: s.start_time.slice(0, 5),
        endTime: s.end_time.slice(0, 5),
        item: s.item,
        autoGenerated: s.auto_generated,
      });
    });

    combined.sort((a, b) => a.startTime.localeCompare(b.startTime));

    const finalTimeline = [];
    let lastEnd = '08:00';

    combined.forEach((entry) => {
      if (entry.startTime > lastEnd) {
        const [h1, m1] = lastEnd.split(':').map(Number);
        const [h2, m2] = entry.startTime.split(':').map(Number);
        const gapMin = (h2 * 60 + m2) - (h1 * 60 + m1);

        if (gapMin >= 15) {
          finalTimeline.push({
            type: 'free',
            id: `free-${lastEnd}-${entry.startTime}`,
            startTime: lastEnd,
            endTime: entry.startTime,
            durationMin: gapMin,
          });
        }
      }
      finalTimeline.push(entry);
      if (entry.endTime > lastEnd) {
        lastEnd = entry.endTime;
      }
    });

    if (lastEnd < '22:00') {
      const [h1, m1] = lastEnd.split(':').map(Number);
      const gapMin = (22 * 60) - (h1 * 60 + m1);
      if (gapMin >= 15) {
        finalTimeline.push({
          type: 'free',
          id: `free-${lastEnd}-22:00`,
          startTime: lastEnd,
          endTime: '22:00',
          durationMin: gapMin,
        });
      }
    }

    return finalTimeline;
  }, [routineBlocks, slots]);

  const formattedDateTitle = useMemo(() => {
    try {
      const d = new Date(selectedDate + 'T00:00:00');
      return d.toLocaleDateString(undefined, {
        weekday: 'long',
        month: 'short',
        day: 'numeric',
      });
    } catch {
      return selectedDate;
    }
  }, [selectedDate]);

  const isToday = selectedDate === getTodayStr();

  return (
    <div className="w-full max-w-3xl mx-auto space-y-5">
      {/* Date Header & Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-[#e2ded5] dark:border-[#383530]">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-semibold text-[#1f1e1d] dark:text-[#ebe8e2] flex items-center gap-2">
              <CalendarDays className="w-4 h-4 text-[#2d553c] dark:text-[#5b8a6c]" />
              {formattedDateTitle}
            </h2>
            {isToday && (
              <span className="px-2 py-0.5 rounded text-[10px] font-semibold uppercase tracking-wider bg-[#2d553c]/10 text-[#2d553c] dark:text-[#5b8a6c]">
                Today
              </span>
            )}
          </div>
          <p className="text-xs text-[#6b6760] dark:text-[#9e998f] mt-0.5">
            Pacing timeline fitting study goals around your fixed commitments.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          {/* Date Navigator */}
          <div className="flex items-center bg-[#f4f2ee] dark:bg-[#282623] rounded-lg p-0.5 border border-[#e2ded5] dark:border-[#383530] text-xs">
            <button
              onClick={() => handleDateChange(-1)}
              className="p-1 rounded text-[#6b6760] hover:text-[#1f1e1d] dark:hover:text-[#ebe8e2] cursor-pointer"
              title="Previous Day"
              aria-label="Previous Day"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            {!isToday && (
              <button
                onClick={() => setSelectedDate(getTodayStr())}
                className="px-2 py-0.5 text-xs font-medium text-[#2d553c] dark:text-[#5b8a6c] hover:bg-[#ffffff] dark:hover:bg-[#1f1e1d] rounded cursor-pointer"
              >
                Today
              </button>
            )}
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="px-1 text-xs bg-transparent text-[#1f1e1d] dark:text-[#ebe8e2] focus:outline-none cursor-pointer"
            />
            <button
              onClick={() => handleDateChange(1)}
              className="p-1 rounded text-[#6b6760] hover:text-[#1f1e1d] dark:hover:text-[#ebe8e2] cursor-pointer"
              title="Next Day"
              aria-label="Next Day"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>

          {/* Trigger Auto-Scheduler */}
          <Button
            variant="primary"
            size="sm"
            onClick={handleRunScheduler}
            disabled={isScheduling}
          >
            {isScheduling ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin mr-1.5" />
            ) : (
              <CalendarCheck className="w-3.5 h-3.5 mr-1.5" />
            )}
            <span>{isScheduling ? 'Scheduling...' : 'Auto-Schedule'}</span>
          </Button>
        </div>
      </div>

      {/* Unplaceable Items Warning Banner */}
      {unplaceableItems.length > 0 && (
        <div className="bg-[#7d3b2b]/10 border border-[#7d3b2b]/20 rounded-xl p-3 text-xs text-[#7d3b2b] dark:text-[#d48372] space-y-1.5">
          <div className="flex items-center gap-2 font-semibold">
            <AlertTriangle className="w-4 h-4 shrink-0" />
            <span>{unplaceableItems.length} item(s) could not fit today</span>
          </div>
          <p className="text-[11px] text-[#6b6760] dark:text-[#9e998f]">
            These exceed remaining open windows today. They remain safely in your inbox for tomorrow:
          </p>
          <ul className="list-disc list-inside space-y-0.5 pl-1 text-[11px]">
            {unplaceableItems.map((it) => (
              <li key={it.id} className="truncate">
                <strong>{it.raw_text}</strong> ({it.est_duration_min || 30}m)
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Timeline Stream */}
      <div className="space-y-2 pt-1">
        {isLoading ? (
          <div className="space-y-3 py-4">
            <Skeleton className="h-12 w-full rounded-xl" />
            <Skeleton className="h-14 w-full rounded-xl" />
            <Skeleton className="h-12 w-full rounded-xl" />
          </div>
        ) : timelineItems.length > 0 ? (
          timelineItems.map((entry) => {
            if (entry.type === 'routine') {
              return (
                <div
                  key={entry.id}
                  className="flex items-center gap-3 bg-[#f4f2ee]/60 dark:bg-[#282623]/60 border border-[#e2ded5] dark:border-[#383530] rounded-xl p-3 text-xs text-[#6b6760] dark:text-[#9e998f]"
                >
                  <div className="w-24 shrink-0 font-mono font-medium text-[11px]">
                    {entry.startTime} – {entry.endTime}
                  </div>
                  <div className="flex items-center gap-2 flex-1 min-w-0">
                    <span className="p-1 rounded bg-[#e2ded5]/60 dark:bg-[#383530] text-[#6b6760] dark:text-[#9e998f]">
                      <Lock className="w-3 h-3" />
                    </span>
                    <span className="font-medium text-[#1f1e1d] dark:text-[#ebe8e2] truncate">
                      {entry.label}
                    </span>
                    <span className="text-[10px] font-medium tracking-wide px-1.5 py-0.2 rounded bg-[#e2ded5]/40 dark:bg-[#383530]/60 text-[#6b6760] dark:text-[#9e998f]">
                      Routine
                    </span>
                  </div>
                </div>
              );
            }

            if (entry.type === 'slot') {
              const item = entry.item;
              const isDone = item?.status === 'done';
              return (
                <div
                  key={entry.id}
                  className={`flex items-start sm:items-center justify-between gap-3 bg-[#ffffff] dark:bg-[#1f1e1d] border rounded-xl p-3.5 shadow-xs transition-all ${
                    isDone
                      ? 'border-[#e2ded5]/60 dark:border-[#383530]/60 opacity-60 bg-[#f4f2ee]/40'
                      : 'border-[#2d553c]/30 dark:border-[#5b8a6c]/30 hover:border-[#2d553c]'
                  }`}
                >
                  <div className="flex items-start sm:items-center gap-3 flex-1 min-w-0">
                    <div className="w-24 shrink-0 font-mono font-semibold text-[#2d553c] dark:text-[#5b8a6c] text-xs">
                      {entry.startTime} – {entry.endTime}
                    </div>

                    <button
                      onClick={() => item && onCompleteItem(item)}
                      className="mt-0.5 sm:mt-0 text-[#6b6760] hover:text-[#2d553c] dark:hover:text-[#5b8a6c] transition-colors cursor-pointer shrink-0 focus:outline-none"
                      title={isDone ? 'Done' : 'Mark done'}
                      aria-label={isDone ? 'Mark as not done' : 'Mark as done'}
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-5 h-5 text-[#2d553c] dark:text-[#5b8a6c]" />
                      ) : (
                        <Circle className="w-5 h-5 hover:scale-105 transition-transform" />
                      )}
                    </button>

                    <div className="flex-1 min-w-0">
                      <p
                        className={`text-sm font-medium text-[#1f1e1d] dark:text-[#ebe8e2] truncate ${
                          isDone ? 'line-through text-[#6b6760] dark:text-[#9e998f]' : ''
                        }`}
                      >
                        {item ? item.raw_text : 'Task'}
                      </p>

                      <div className="flex items-center gap-1.5 mt-1 text-[10px]">
                        {item?.category && (
                          <Badge variant={item.category}>
                            {item.category}
                          </Badge>
                        )}

                        {item?.priority && (
                          <Badge variant={item.priority >= 4 ? 'priority-high' : 'priority-mid'}>
                            P{item.priority}
                          </Badge>
                        )}

                        {item?.est_duration_min && (
                          <span className="text-[#6b6760] dark:text-[#9e998f] flex items-center gap-0.5">
                            <Clock className="w-3 h-3" />
                            {item.est_duration_min}m
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            }

            if (entry.type === 'free') {
              return (
                <div
                  key={entry.id}
                  className="flex items-center gap-3 px-3 py-1.5 border border-dashed border-[#e2ded5] dark:border-[#383530] rounded-lg text-xs text-[#9e998f]"
                >
                  <div className="w-24 shrink-0 font-mono text-[11px] text-[#9e998f]">
                    {entry.startTime} – {entry.endTime}
                  </div>
                  <div className="flex items-center gap-1.5 text-[11px] text-[#6b6760] dark:text-[#9e998f]">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#2d553c]" />
                    <span>Free slot ({entry.durationMin}m open)</span>
                  </div>
                </div>
              );
            }

            return null;
          })
        ) : (
          <EmptyState
            icon={CalendarDays}
            title={`No tasks scheduled for ${formattedDateTitle}`}
            description="Click 'Auto-Schedule' to fit your inbox items into today's open windows around your classes and commitments."
            actionLabel={isScheduling ? 'Scheduling...' : `Auto-Schedule ${isToday ? 'Today' : 'This Day'}`}
            onAction={handleRunScheduler}
          />
        )}
      </div>
    </div>
  );
}
