import React, { useState, useEffect, useMemo } from 'react';
import {
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Sparkles,
  Clock,
  Lock,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  Layers,
  Circle,
} from 'lucide-react';
import { fetchSchedule, runScheduler } from '../api/schedule';
import { fetchRoutineBlocks } from '../api/routine';

export default function TimelineView({ onCompleteItem, onToast }) {
  const getTodayStr = () => new Date().toISOString().split('T')[0];

  const [selectedDate, setSelectedDate] = useState(getTodayStr);
  const [slots, setSlots] = useState([]);
  const [routineBlocks, setRoutineBlocks] = useState([]);
  const [unplaceableItems, setUnplaceableItems] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isScheduling, setIsScheduling] = useState(false);

  // Load schedule slots and routine blocks for selected date
  const loadDayData = async (targetDate = selectedDate) => {
    setIsLoading(true);
    try {
      const d = new Date(targetDate + 'T00:00:00');
      // Python weekday: 0=Monday, 6=Sunday. JS getDay(): 0=Sunday, 1=Monday...
      const jsDay = d.getDay();
      const pythonWeekday = jsDay === 0 ? 6 : jsDay - 1;

      const [slotsData, routineData] = await Promise.all([
        fetchSchedule(targetDate),
        fetchRoutineBlocks(pythonWeekday),
      ]);

      setSlots(slotsData);
      setRoutineBlocks(routineData);
    } catch (err) {
      onToast?.(err.message || 'Failed to load timeline', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadDayData(selectedDate);
  }, [selectedDate]);

  const handleDateChange = (daysDelta) => {
    const current = new Date(selectedDate + 'T00:00:00');
    current.setDate(current.getDate() + daysDelta);
    const newDateStr = current.toISOString().split('T')[0];
    setSelectedDate(newDateStr);
  };

  const handleRunScheduler = async () => {
    setIsScheduling(true);
    try {
      const result = await runScheduler(selectedDate);
      setSlots(result.slots || []);
      setUnplaceableItems(result.unplaceable_items || []);

      if (result.scheduled_count > 0) {
        onToast?.(`Scheduled ${result.scheduled_count} item(s)!`);
      } else if (result.unplaceable_count > 0) {
        onToast?.(`No free slots available for remaining items`, 'error');
      } else {
        onToast?.('Schedule up to date — no pending items');
      }
    } catch (err) {
      onToast?.(err.message || 'Failed to run scheduler', 'error');
    } finally {
      setIsScheduling(false);
    }
  };

  // Merge routine blocks and schedule slots into a single chronological timeline
  const timelineItems = useMemo(() => {
    const combined = [];

    // Routine blocks
    routineBlocks.forEach((rb) => {
      combined.push({
        type: 'routine',
        id: `rb-${rb.id}`,
        startTime: rb.start_time.slice(0, 5),
        endTime: rb.end_time.slice(0, 5),
        label: rb.label || 'Routine Block',
        fixed: rb.fixed,
      });
    });

    // Scheduled task slots
    slots.forEach((s) => {
      combined.push({
        type: 'slot',
        id: `slot-${s.id}`,
        slotId: s.id,
        startTime: s.start_time.slice(0, 5),
        endTime: s.end_time.slice(0, 5),
        item: s.item,
        autoGenerated: s.auto_generated,
      });
    });

    // Sort chronologically
    combined.sort((a, b) => a.startTime.localeCompare(b.startTime));

    // Calculate free gaps between 08:00 and 22:00
    const finalTimeline = [];
    let lastEnd = '08:00';

    combined.forEach((entry) => {
      if (entry.startTime > lastEnd) {
        // Compute duration of gap in minutes
        const [h1, m1] = lastEnd.split(':').map(Number);
        const [h2, m2] = entry.startTime.split(':').map(Number);
        const gapMin = (h2 * 60 + m2) - (h1 * 60 + m1);

        if (gapMin >= 15) {
          finalTimeline.push({
            type: 'free',
            id: `free-${lastEnd}-${entry.startTime}`,
            startTime: lastEnd,
            endTime: entry.startTime,
            durationMin: gapMin,
          });
        }
      }
      finalTimeline.push(entry);
      if (entry.endTime > lastEnd) {
        lastEnd = entry.endTime;
      }
    });

    // Check if free time remains until 22:00
    if (lastEnd < '22:00') {
      const [h1, m1] = lastEnd.split(':').map(Number);
      const gapMin = (22 * 60) - (h1 * 60 + m1);
      if (gapMin >= 15) {
        finalTimeline.push({
          type: 'free',
          id: `free-${lastEnd}-22:00`,
          startTime: lastEnd,
          endTime: '22:00',
          durationMin: gapMin,
        });
      }
    }

    return finalTimeline;
  }, [routineBlocks, slots]);

  const formattedDateTitle = useMemo(() => {
    try {
      const d = new Date(selectedDate + 'T00:00:00');
      return d.toLocaleDateString(undefined, {
        weekday: 'long',
        month: 'short',
        day: 'numeric',
      });
    } catch {
      return selectedDate;
    }
  }, [selectedDate]);

  const isToday = selectedDate === getTodayStr();

  const priorityStyles = {
    5: 'bg-red-500 text-white',
    4: 'bg-orange-500 text-white',
    3: 'bg-yellow-500 text-white',
    2: 'bg-blue-400 text-white',
    1: 'bg-slate-400 text-white',
  };

  const categoryStyles = {
    task: 'bg-blue-50 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300 border-blue-200 dark:border-blue-900',
    idea: 'bg-amber-50 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-900',
    reminder: 'bg-purple-50 text-purple-700 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-900',
    deadline: 'bg-rose-50 text-rose-700 dark:bg-rose-950/60 dark:text-rose-300 border-rose-200 dark:border-rose-900',
  };

  return (
    <div className="w-full max-w-3xl mx-auto space-y-6">
      {/* Date Header & Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-200 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <CalendarDays className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              {formattedDateTitle}
            </h2>
            {isToday && (
              <span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-indigo-100 dark:bg-indigo-950/80 text-indigo-700 dark:text-indigo-300">
                Today
              </span>
            )}
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Auto-scheduled timeline fitting inbox items around fixed commitments.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          {/* Date Navigator */}
          <div className="flex items-center bg-slate-100 dark:bg-slate-900 rounded-xl p-1 border border-slate-200 dark:border-slate-800 text-xs">
            <button
              onClick={() => handleDateChange(-1)}
              className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-800 cursor-pointer"
              title="Previous Day"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            {!isToday && (
              <button
                onClick={() => setSelectedDate(getTodayStr())}
                className="px-2 py-1 text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:bg-white dark:hover:bg-slate-800 rounded-lg cursor-pointer"
              >
                Today
              </button>
            )}
            <input
              type="date"
              value={selectedDate}
              onChange={(e) => setSelectedDate(e.target.value)}
              className="px-1 text-xs bg-transparent text-slate-700 dark:text-slate-300 focus:outline-none cursor-pointer"
            />
            <button
              onClick={() => handleDateChange(1)}
              className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-white dark:hover:bg-slate-800 cursor-pointer"
              title="Next Day"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>

          {/* Trigger Auto-Scheduler */}
          <button
            onClick={handleRunScheduler}
            disabled={isScheduling}
            className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 text-white font-semibold text-xs shadow-sm transition-all cursor-pointer disabled:opacity-50"
          >
            {isScheduling ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Sparkles className="w-3.5 h-3.5" />
            )}
            <span>{isScheduling ? 'Scheduling...' : 'Auto-Schedule'}</span>
          </button>
        </div>
      </div>

      {/* Unplaceable Items Warning Banner */}
      {unplaceableItems.length > 0 && (
        <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900 rounded-2xl p-4 text-xs text-amber-900 dark:text-amber-200 space-y-2">
          <div className="flex items-center gap-2 font-bold text-amber-800 dark:text-amber-300">
            <AlertTriangle className="w-4 h-4 text-amber-600" />
            <span>{unplaceableItems.length} item(s) could not fit today</span>
          </div>
          <p className="text-[11px] text-amber-700 dark:text-amber-400">
            These items exceed the remaining free time intervals or break buffers today. They remain safely in your inbox for tomorrow:
          </p>
          <ul className="list-disc list-inside space-y-1 pl-1">
            {unplaceableItems.map((it) => (
              <li key={it.id} className="truncate">
                <strong>{it.raw_text}</strong> ({it.est_duration_min || 30}m)
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Timeline Stream */}
      <div className="space-y-2 pt-1">
        {isLoading ? (
          <div className="py-16 text-center text-slate-400 text-sm">
            <Clock className="w-6 h-6 mx-auto animate-spin mb-2 opacity-50" />
            Loading day schedule...
          </div>
        ) : timelineItems.length > 0 ? (
          timelineItems.map((entry) => {
            // 1. Routine block
            if (entry.type === 'routine') {
              return (
                <div
                  key={entry.id}
                  className="flex items-center gap-3 bg-slate-100/80 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800/80 rounded-xl p-3.5 text-xs text-slate-600 dark:text-slate-400"
                >
                  <div className="w-24 shrink-0 font-mono font-semibold text-slate-500 text-[11px]">
                    {entry.startTime} – {entry.endTime}
                  </div>
                  <div className="flex items-center gap-2 flex-1 min-w-0">
                    <span className="p-1 rounded bg-slate-200 dark:bg-slate-800 text-slate-500">
                      <Lock className="w-3.5 h-3.5" />
                    </span>
                    <span className="font-semibold text-slate-800 dark:text-slate-200 truncate">
                      {entry.label}
                    </span>
                    <span className="text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.2 rounded bg-slate-200/80 dark:bg-slate-800 text-slate-500">
                      Routine
                    </span>
                  </div>
                </div>
              );
            }

            // 2. Scheduled Task slot
            if (entry.type === 'slot') {
              const item = entry.item;
              const isDone = item?.status === 'done';
              return (
                <div
                  key={entry.id}
                  className={`flex items-start sm:items-center justify-between gap-3 bg-white dark:bg-slate-900 border rounded-xl p-3.5 shadow-xs transition-all ${
                    isDone
                      ? 'border-slate-200 dark:border-slate-800 opacity-60 bg-slate-50/50'
                      : 'border-indigo-100 dark:border-indigo-950/80 hover:border-indigo-300'
                  }`}
                >
                  <div className="flex items-start sm:items-center gap-3 flex-1 min-w-0">
                    <div className="w-24 shrink-0 font-mono font-bold text-indigo-600 dark:text-indigo-400 text-xs">
                      {entry.startTime} – {entry.endTime}
                    </div>

                    <button
                      onClick={() => item && onCompleteItem(item)}
                      className="mt-0.5 sm:mt-0 text-slate-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors cursor-pointer shrink-0 focus:outline-none"
                      title={isDone ? 'Done' : 'Mark done'}
                    >
                      {isDone ? (
                        <CheckCircle2 className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                      ) : (
                        <Circle className="w-5 h-5 hover:scale-110 transition-transform" />
                      )}
                    </button>

                    <div className="flex-1 min-w-0">
                      <p
                        className={`text-sm font-semibold text-slate-900 dark:text-slate-100 truncate ${
                          isDone ? 'line-through text-slate-400' : ''
                        }`}
                      >
                        {item ? item.raw_text : 'Task'}
                      </p>

                      <div className="flex items-center gap-1.5 mt-1 text-[10px]">
                        {item?.category && (
                          <span
                            className={`px-1.5 py-0.2 rounded-full font-medium border capitalize ${
                              categoryStyles[item.category] || 'bg-slate-100 text-slate-600'
                            }`}
                          >
                            {item.category}
                          </span>
                        )}

                        {item?.priority && (
                          <span
                            className={`px-1.5 py-0.2 rounded font-semibold ${
                              priorityStyles[item.priority] || 'bg-slate-400 text-white'
                            }`}
                          >
                            P{item.priority}
                          </span>
                        )}

                        {item?.est_duration_min && (
                          <span className="text-slate-400 flex items-center gap-0.5">
                            <Clock className="w-3 h-3" />
                            {item.est_duration_min}m
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>
              );
            }

            // 3. Free time interval
            if (entry.type === 'free') {
              return (
                <div
                  key={entry.id}
                  className="flex items-center gap-3 px-4 py-2 border border-dashed border-slate-200 dark:border-slate-800/80 rounded-xl text-xs text-slate-400"
                >
                  <div className="w-24 shrink-0 font-mono text-[11px] text-slate-400">
                    {entry.startTime} – {entry.endTime}
                  </div>
                  <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                    <span>Free slot ({entry.durationMin}m available)</span>
                  </div>
                </div>
              );
            }

            return null;
          })
        ) : (
          <div className="text-center py-16 border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-2xl p-8">
            <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/50 text-indigo-600 dark:text-indigo-400 mx-auto flex items-center justify-center mb-3">
              <CalendarDays className="w-6 h-6" />
            </div>
            <h3 className="text-slate-800 dark:text-slate-200 font-semibold text-base mb-1">
              No tasks scheduled for {formattedDateTitle}
            </h3>
            <p className="text-slate-400 text-xs max-w-sm mx-auto mb-4">
              Click "Auto-Schedule" above to greedily fit your inbox items into today's open windows.
            </p>
            <button
              onClick={handleRunScheduler}
              disabled={isScheduling}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs shadow-sm transition-all cursor-pointer"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>Auto-Schedule {isToday ? 'Today' : 'This Day'}</span>
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

