"""initial_schema

Revision ID: e1bb4c49e1e1
Revises: 
Create Date: 2026-09-23 16:41:05.334292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bb4c49e1e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('est_duration_min', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='inbox', nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('task', 'idea', 'reminder', 'deadline')", name='check_item_category'),
    sa.CheckConstraint("status IN ('inbox', 'scheduled', 'done', 'skipped')", name='check_item_status'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='check_item_priority'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)

    op.create_table('routine_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('fixed', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='check_routine_day_of_week'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routine_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_blocks_id'), ['id'], unique=False)

    op.create_table('user_prefs',
    sa.Column('user_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('preferred_deep_hours', sa.Text(), nullable=True),
    sa.Column('break_duration_pref', sa.Integer(), server_default='10', nullable=False),
    sa.Column('category_duration_multiplier', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('feedback_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('suggestion_accepted', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_log_id'), ['id'], unique=False)

    op.create_table('schedule_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_slots_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_slots_id'))

    op.drop_table('schedule_slots')
    with op.batch_alter_table('feedback_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_log_id'))

    op.drop_table('feedback_log')
    op.drop_table('user_prefs')
    with op.batch_alter_table('routine_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_blocks_id'))

    op.drop_table('routine_blocks')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_id'))

    op.drop_table('items')
    # ### end Alembic commands ###
