from typing import List, Dict, Any

LABELED_EXAMPLES: List[Dict[str, Any]] = [
    # --- TASK (25 examples) ---
    {"text": "Clean out the gutters this weekend", "category": "task", "priority": 3},
    {"text": "Book flights for December holidays", "category": "task", "priority": 3},
    {"text": "Send contract to client for signature", "category": "task", "priority": 4},
    {"text": "Update database schema for user profiles", "category": "task", "priority": 3},
    {"text": "Call the plumber about leaking kitchen sink", "category": "task", "priority": 4},
    {"text": "Order more printer paper and pens", "category": "task", "priority": 2},
    {"text": "Review pull request on github repository", "category": "task", "priority": 4},
    {"text": "Prepare slide deck for investor pitch", "category": "task", "priority": 5},
    {"text": "Pick up dry cleaning on the way home", "category": "task", "priority": 2},
    {"text": "File expense reports from conference", "category": "task", "priority": 3},
    {"text": "Change air filters in furnace", "category": "task", "priority": 3},
    {"text": "Renew car registration online", "category": "task", "priority": 4},
    {"text": "Draft release notes for version 2.0", "category": "task", "priority": 3},
    {"text": "Refactor authentication middleware", "category": "task", "priority": 4},
    {"text": "Schedule annual dental cleaning", "category": "task", "priority": 3},
    {"text": "Take cat to veterinary appointment", "category": "task", "priority": 4},
    {"text": "Water vegetable garden before noon", "category": "task", "priority": 2},
    {"text": "Pack luggage for upcoming business trip", "category": "task", "priority": 4},
    {"text": "Write unit tests for checkout flow", "category": "task", "priority": 4},
    {"text": "Cancel unused streaming subscription", "category": "task", "priority": 2},
    {"text": "Empty recycling bins and take trash out", "category": "task", "priority": 2},
    {"text": "Install security updates on home server", "category": "task", "priority": 4},
    {"text": "Assemble new standing desk furniture", "category": "task", "priority": 3},
    {"text": "Mow the front and backyard lawn", "category": "task", "priority": 2},
    {"text": "Wash bed sheets and duvet covers", "category": "task", "priority": 2},

    # --- IDEA (25 examples) ---
    {"text": "What if we built an offline-first markdown journal", "category": "idea", "priority": 2},
    {"text": "Potential concept for multiplayer canvas game", "category": "idea", "priority": 2},
    {"text": "Look into using Rust for audio processing", "category": "idea", "priority": 3},
    {"text": "Explore generative UI patterns for dashboards", "category": "idea", "priority": 3},
    {"text": "A recipe recommender based on pantry ingredients", "category": "idea", "priority": 2},
    {"text": "Read up on CRDT algorithms for collaborative editing", "category": "idea", "priority": 3},
    {"text": "Brainstorm names for productivity side project", "category": "idea", "priority": 2},
    {"text": "Consider adopting micro-frontends architecture", "category": "idea", "priority": 3},
    {"text": "Maybe try intermittent fasting next month", "category": "idea", "priority": 2},
    {"text": "Research solar panel efficiency ratings", "category": "idea", "priority": 2},
    {"text": "Thoughts on minimalist desk setup configurations", "category": "idea", "priority": 1},
    {"text": "Explore WebAssembly for browser video encoding", "category": "idea", "priority": 3},
    {"text": "Book idea about history of mechanical keyboards", "category": "idea", "priority": 1},
    {"text": "Concept for ambient sound generator app", "category": "idea", "priority": 2},
    {"text": "Research tree-shaking techniques for bundling", "category": "idea", "priority": 3},
    {"text": "Could use vector embeddings for bookmark search", "category": "idea", "priority": 3},
    {"text": "Investigate local LLM inference on consumer GPUs", "category": "idea", "priority": 3},
    {"text": "Experiment with color palettes inspired by nature", "category": "idea", "priority": 1},
    {"text": "Explore pottery classes in the neighborhood", "category": "idea", "priority": 2},
    {"text": "Idea for podcast discussing indie software businesses", "category": "idea", "priority": 2},
    {"text": "Study principles of Scandinavian interior design", "category": "idea", "priority": 1},
    {"text": "Look into electric bicycle conversion kits", "category": "idea", "priority": 2},
    {"text": "Thoughts on asynchronous remote work communication", "category": "idea", "priority": 2},
    {"text": "Curiosity about how mechanical watches work", "category": "idea", "priority": 1},
    {"text": "Possibility of converting old laptop into a NAS", "category": "idea", "priority": 2},

    # --- REMINDER (25 examples) ---
    {"text": "Don't forget to take vitamins with breakfast", "category": "reminder", "priority": 3},
    {"text": "Remember to turn off irrigation sprinklers", "category": "reminder", "priority": 3},
    {"text": "Check oven timer in 20 minutes", "category": "reminder", "priority": 4},
    {"text": "Remind me to call grandma this evening", "category": "reminder", "priority": 3},
    {"text": "Notify me when laundry wash cycle completes", "category": "reminder", "priority": 2},
    {"text": "Remember to lock front door when leaving", "category": "reminder", "priority": 4},
    {"text": "Don't leave umbrella in the subway", "category": "reminder", "priority": 3},
    {"text": "Remind me to drink a glass of water every hour", "category": "reminder", "priority": 2},
    {"text": "Remember to bring passport to airport tomorrow", "category": "reminder", "priority": 5},
    {"text": "Check if sourdough starter needs feeding", "category": "reminder", "priority": 2},
    {"text": "Don't forget to defrost chicken in refrigerator", "category": "reminder", "priority": 3},
    {"text": "Remind me to wish Sarah happy birthday", "category": "reminder", "priority": 3},
    {"text": "Turn down air conditioner before going to sleep", "category": "reminder", "priority": 2},
    {"text": "Remember to mute microphone during webinar", "category": "reminder", "priority": 3},
    {"text": "Check tire pressure before long road trip", "category": "reminder", "priority": 4},
    {"text": "Don't forget house keys on dining table", "category": "reminder", "priority": 4},
    {"text": "Take evening blood pressure medication after dinner", "category": "reminder", "priority": 5},
    {"text": "Remember to unplug electric heater after use", "category": "reminder", "priority": 4},
    {"text": "Remind me to check postal mailbox today", "category": "reminder", "priority": 2},
    {"text": "Don't forget reusable grocery bags in trunk", "category": "reminder", "priority": 1},
    {"text": "Remember to charge wireless mouse overnight", "category": "reminder", "priority": 2},
    {"text": "Check departure terminal number before train arrives", "category": "reminder", "priority": 3},
    {"text": "Remember to return borrowed library books", "category": "reminder", "priority": 2},
    {"text": "Don't forget laptop charger for office day", "category": "reminder", "priority": 4},
    {"text": "Remind me to stretch every 45 minutes", "category": "reminder", "priority": 2},

    # --- DEADLINE (25 examples) ---
    {"text": "Federal tax return submission deadline April 15", "category": "deadline", "priority": 5},
    {"text": "College grant application due by end of month", "category": "deadline", "priority": 5},
    {"text": "Final manuscript submission cutoff Friday afternoon", "category": "deadline", "priority": 4},
    {"text": "Passport renewal documents must be submitted today", "category": "deadline", "priority": 5},
    {"text": "Quarterly VAT filing deadline October 20", "category": "deadline", "priority": 5},
    {"text": "Conference research paper submission deadline midnight", "category": "deadline", "priority": 5},
    {"text": "Health insurance open enrollment closes this week", "category": "deadline", "priority": 4},
    {"text": "Project proposal hard deadline next Tuesday 5pm", "category": "deadline", "priority": 5},
    {"text": "Patent response filing cutoff date", "category": "deadline", "priority": 4},
    {"text": "University tuition fee payment due date", "category": "deadline", "priority": 5},
    {"text": "Annual performance review self-assessment due", "category": "deadline", "priority": 4},
    {"text": "Legal contract response deadline expires tomorrow", "category": "deadline", "priority": 5},
    {"text": "Final exam assignment submission portal closes", "category": "deadline", "priority": 5},
    {"text": "Design contest entry deadline end of day", "category": "deadline", "priority": 4},
    {"text": "Apartment lease renewal decision deadline", "category": "deadline", "priority": 4},
    {"text": "Product warranty claim expiration date approaching", "category": "deadline", "priority": 3},
    {"text": "Scholarship application materials due November 1", "category": "deadline", "priority": 4},
    {"text": "Financial audit document submission cutoff", "category": "deadline", "priority": 4},
    {"text": "Annual vehicle emissions inspection deadline", "category": "deadline", "priority": 4},
    {"text": "Contractor bid submission deadline 5pm", "category": "deadline", "priority": 4},
    {"text": "Semester grade submission deadline for faculty", "category": "deadline", "priority": 4},
    {"text": "Software subscription renewal cutoff date", "category": "deadline", "priority": 3},
    {"text": "Job offer response deadline expires Monday", "category": "deadline", "priority": 5},
    {"text": "Conference registration early bird discount deadline", "category": "deadline", "priority": 3},
    {"text": "Building permit extension application deadline", "category": "deadline", "priority": 4},
]

